--------------------------------------------------------
--  File created - Четвъртък-Октомври-22-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEPARTMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9990 INCREMENT BY 10 START WITH 280 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 207 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOCATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."LOCATIONS_SEQ"  MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "HR"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"NAME_CLIENT" VARCHAR2(20 BYTE), 
	"EGN_CLIENT" VARCHAR2(10 BYTE), 
	"PHONE_CLIENT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURIER
--------------------------------------------------------

  CREATE TABLE "HR"."COURIER" 
   (	"ID_COURIER" NUMBER(*,0), 
	"NAME_COURIER" VARCHAR2(20 BYTE), 
	"PHONE_COURIER" VARCHAR2(10 BYTE), 
	"OFFICE_ID_OFFICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INFO_PACKAGE
--------------------------------------------------------

  CREATE TABLE "HR"."INFO_PACKAGE" 
   (	"ID_INFO_PAKAGE" NUMBER(*,0), 
	"SENT_FROM" VARCHAR2(15 BYTE), 
	"DELIVERED_TO" VARCHAR2(15 BYTE), 
	"DATE_PACKAGE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFFICE
--------------------------------------------------------

  CREATE TABLE "HR"."OFFICE" 
   (	"ID_OFFICE" NUMBER(*,0), 
	"LOCATION_OFFICE" VARCHAR2(30 BYTE), 
	"OPEN_OFFICE" TIMESTAMP (6), 
	"CLOSE_OFFICE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACKAGE
--------------------------------------------------------

  CREATE TABLE "HR"."PACKAGE" 
   (	"ID_PACKAGE" NUMBER(*,0), 
	"NAME_PACKAGE" VARCHAR2(20 BYTE), 
	"TYPE_PACKAGE_ID" NUMBER(*,0), 
	"PACKAGE_SATUS_ID" NUMBER(*,0), 
	"REGISTRY_ID_REGISTRY" NUMBER(*,0), 
	"INFO_PACKAGE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACKAGE_SATUS
--------------------------------------------------------

  CREATE TABLE "HR"."PACKAGE_SATUS" 
   (	"ID_STATUS_PACKAGE" NUMBER(*,0), 
	"TYPE_STATUS" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTRY
--------------------------------------------------------

  CREATE TABLE "HR"."REGISTRY" 
   (	"ID_REGISTRY" NUMBER(*,0), 
	"DATE_REGISTRY" DATE, 
	"CLIENT_ID_CLIENT" NUMBER(*,0), 
	"COURIER_ID_COURIER" NUMBER(*,0), 
	"TRANSP_PACKAGE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSPORT_PACKAGE
--------------------------------------------------------

  CREATE TABLE "HR"."TRANSPORT_PACKAGE" 
   (	"ID_TRANSPORT_PACKAGE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE_PACKAGE
--------------------------------------------------------

  CREATE TABLE "HR"."TYPE_PACKAGE" 
   (	"ID_TYPE_PACKAGE" NUMBER(*,0), 
	"TYPE_PACKAGE" VARCHAR2(15 BYTE), 
	"PRICE_PACKAGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View EMP_DETAILS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HR"."EMP_DETAILS_VIEW" ("EMPLOYEE_ID", "JOB_ID", "MANAGER_ID", "DEPARTMENT_ID", "LOCATION_ID", "COUNTRY_ID", "FIRST_NAME", "LAST_NAME", "SALARY", "COMMISSION_PCT", "DEPARTMENT_NAME", "JOB_TITLE", "CITY", "STATE_PROVINCE", "COUNTRY_NAME", "REGION_NAME") AS 
  SELECT
  e.employee_id,
  e.job_id,
  e.manager_id,
  e.department_id,
  d.location_id,
  l.country_id,
  e.first_name,
  e.last_name,
  e.salary,
  e.commission_pct,
  d.department_name,
  j.job_title,
  l.city,
  l.state_province,
  c.country_name,
  r.region_name
FROM
  employees e,
  departments d,
  jobs j,
  locations l,
  countries c,
  regions r
WHERE e.department_id = d.department_id
  AND d.location_id = l.location_id
  AND l.country_id = c.country_id
  AND c.region_id = r.region_id
  AND j.job_id = e.job_id
WITH READ ONLY
;
REM INSERTING into HR.CLIENT
SET DEFINE OFF;
Insert into HR.CLIENT (ID_CLIENT,NAME_CLIENT,EGN_CLIENT,PHONE_CLIENT) values (1,'Angel','9204041213','0897363683');
Insert into HR.CLIENT (ID_CLIENT,NAME_CLIENT,EGN_CLIENT,PHONE_CLIENT) values (2,'Bojidar','9506043300','0897180456');
REM INSERTING into HR.COURIER
SET DEFINE OFF;
Insert into HR.COURIER (ID_COURIER,NAME_COURIER,PHONE_COURIER,OFFICE_ID_OFFICE) values (1,'Mihail','0894344521',2);
REM INSERTING into HR.INFO_PACKAGE
SET DEFINE OFF;
Insert into HR.INFO_PACKAGE (ID_INFO_PAKAGE,SENT_FROM,DELIVERED_TO,DATE_PACKAGE) values (1,'Sofiq','Varna',to_date('2020-10-18','RRRR-MM-DD'));
REM INSERTING into HR.OFFICE
SET DEFINE OFF;
Insert into HR.OFFICE (ID_OFFICE,LOCATION_OFFICE,OPEN_OFFICE,CLOSE_OFFICE) values (3,'gr.Plovdiv,Vladislavovo 8',to_timestamp('09:00:00','HH24:MI:SS'),to_timestamp('17:30:00','HH24:MI:SS'));
Insert into HR.OFFICE (ID_OFFICE,LOCATION_OFFICE,OPEN_OFFICE,CLOSE_OFFICE) values (1,'gr.Varna,Ul.Studentska 3',to_timestamp('09:00:00','HH24:MI:SS'),to_timestamp('18:00:00','HH24:MI:SS'));
Insert into HR.OFFICE (ID_OFFICE,LOCATION_OFFICE,OPEN_OFFICE,CLOSE_OFFICE) values (2,'gr.Sofiq,Mladost 5',to_timestamp('08:30:00','HH24:MI:SS'),to_timestamp('17:00:00','HH24:MI:SS'));
REM INSERTING into HR.PACKAGE
SET DEFINE OFF;
Insert into HR.PACKAGE (ID_PACKAGE,NAME_PACKAGE,TYPE_PACKAGE_ID,PACKAGE_SATUS_ID,REGISTRY_ID_REGISTRY,INFO_PACKAGE_ID) values (1,'Telefon',2,1,1,1);
REM INSERTING into HR.PACKAGE_SATUS
SET DEFINE OFF;
Insert into HR.PACKAGE_SATUS (ID_STATUS_PACKAGE,TYPE_STATUS) values (1,'poluchena');
Insert into HR.PACKAGE_SATUS (ID_STATUS_PACKAGE,TYPE_STATUS) values (2,'nepoluchena');
Insert into HR.PACKAGE_SATUS (ID_STATUS_PACKAGE,TYPE_STATUS) values (3,'otkazana');
REM INSERTING into HR.REGISTRY
SET DEFINE OFF;
Insert into HR.REGISTRY (ID_REGISTRY,DATE_REGISTRY,CLIENT_ID_CLIENT,COURIER_ID_COURIER,TRANSP_PACKAGE_ID) values (1,to_date('2020-10-18','RRRR-MM-DD'),1,1,2);
REM INSERTING into HR.TRANSPORT_PACKAGE
SET DEFINE OFF;
Insert into HR.TRANSPORT_PACKAGE (ID_TRANSPORT_PACKAGE) values (1);
Insert into HR.TRANSPORT_PACKAGE (ID_TRANSPORT_PACKAGE) values (2);
Insert into HR.TRANSPORT_PACKAGE (ID_TRANSPORT_PACKAGE) values (3);
REM INSERTING into HR.TYPE_PACKAGE
SET DEFINE OFF;
Insert into HR.TYPE_PACKAGE (ID_TYPE_PACKAGE,TYPE_PACKAGE,PRICE_PACKAGE) values (1,'plik',5);
Insert into HR.TYPE_PACKAGE (ID_TYPE_PACKAGE,TYPE_PACKAGE,PRICE_PACKAGE) values (2,'kolet',10);
Insert into HR.TYPE_PACKAGE (ID_TYPE_PACKAGE,TYPE_PACKAGE,PRICE_PACKAGE) values (3,'golqm paket',12.5);
Insert into HR.TYPE_PACKAGE (ID_TYPE_PACKAGE,TYPE_PACKAGE,PRICE_PACKAGE) values (4,'tovar',17.5);
REM INSERTING into HR.EMP_DETAILS_VIEW
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CLIENT_PK" ON "HR"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."COURIER_PK" ON "HR"."COURIER" ("ID_COURIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INFO_PACKAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."INFO_PACKAGE_PK" ON "HR"."INFO_PACKAGE" ("ID_INFO_PAKAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."OFFICE_PK" ON "HR"."OFFICE" ("ID_OFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PACKAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PACKAGE_PK" ON "HR"."PACKAGE" ("ID_PACKAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PACKAGE_SATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PACKAGE_SATUS_PK" ON "HR"."PACKAGE_SATUS" ("ID_STATUS_PACKAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGISTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."REGISTRY_PK" ON "HR"."REGISTRY" ("ID_REGISTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSPORT_PACKAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TRANSPORT_PACKAGE_PK" ON "HR"."TRANSPORT_PACKAGE" ("ID_TRANSPORT_PACKAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPE_PACKAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TYPE_PACKAGE_PK" ON "HR"."TYPE_PACKAGE" ("ID_TYPE_PACKAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure ADD_JOB_HISTORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HR"."ADD_JOB_HISTORY" 
  (  p_emp_id          job_history.employee_id%type
   , p_start_date      job_history.start_date%type
   , p_end_date        job_history.end_date%type
   , p_job_id          job_history.job_id%type
   , p_department_id   job_history.department_id%type
   )
IS
BEGIN
  INSERT INTO job_history (employee_id, start_date, end_date,
                           job_id, department_id)
    VALUES(p_emp_id, p_start_date, p_end_date, p_job_id, p_department_id);
END add_job_history;

/
--------------------------------------------------------
--  DDL for Procedure SECURE_DML
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HR"."SECURE_DML" 
IS
BEGIN
  IF TO_CHAR (SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '18:00'
        OR TO_CHAR (SYSDATE, 'DY') IN ('SAT', 'SUN') THEN
	RAISE_APPLICATION_ERROR (-20205,
		'You may only make changes during normal office hours');
  END IF;
END secure_dml;

/
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "HR"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURIER
--------------------------------------------------------

  ALTER TABLE "HR"."COURIER" ADD CONSTRAINT "COURIER_PK" PRIMARY KEY ("ID_COURIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."COURIER" MODIFY ("OFFICE_ID_OFFICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."COURIER" MODIFY ("ID_COURIER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INFO_PACKAGE
--------------------------------------------------------

  ALTER TABLE "HR"."INFO_PACKAGE" ADD CONSTRAINT "INFO_PACKAGE_PK" PRIMARY KEY ("ID_INFO_PAKAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."INFO_PACKAGE" MODIFY ("ID_INFO_PAKAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "HR"."OFFICE" ADD CONSTRAINT "OFFICE_PK" PRIMARY KEY ("ID_OFFICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."OFFICE" MODIFY ("ID_OFFICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACKAGE
--------------------------------------------------------

  ALTER TABLE "HR"."PACKAGE" ADD CONSTRAINT "PACKAGE_PK" PRIMARY KEY ("ID_PACKAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PACKAGE" MODIFY ("INFO_PACKAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PACKAGE" MODIFY ("REGISTRY_ID_REGISTRY" NOT NULL ENABLE);
  ALTER TABLE "HR"."PACKAGE" MODIFY ("PACKAGE_SATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PACKAGE" MODIFY ("TYPE_PACKAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PACKAGE" MODIFY ("ID_PACKAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACKAGE_SATUS
--------------------------------------------------------

  ALTER TABLE "HR"."PACKAGE_SATUS" ADD CONSTRAINT "PACKAGE_SATUS_PK" PRIMARY KEY ("ID_STATUS_PACKAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PACKAGE_SATUS" MODIFY ("ID_STATUS_PACKAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTRY
--------------------------------------------------------

  ALTER TABLE "HR"."REGISTRY" ADD CONSTRAINT "REGISTRY_PK" PRIMARY KEY ("ID_REGISTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."REGISTRY" MODIFY ("TRANSP_PACKAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRY" MODIFY ("COURIER_ID_COURIER" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRY" MODIFY ("CLIENT_ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRY" MODIFY ("ID_REGISTRY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSPORT_PACKAGE
--------------------------------------------------------

  ALTER TABLE "HR"."TRANSPORT_PACKAGE" ADD CONSTRAINT "TRANSPORT_PACKAGE_PK" PRIMARY KEY ("ID_TRANSPORT_PACKAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TRANSPORT_PACKAGE" MODIFY ("ID_TRANSPORT_PACKAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPE_PACKAGE
--------------------------------------------------------

  ALTER TABLE "HR"."TYPE_PACKAGE" ADD CONSTRAINT "TYPE_PACKAGE_PK" PRIMARY KEY ("ID_TYPE_PACKAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TYPE_PACKAGE" MODIFY ("ID_TYPE_PACKAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COURIER
--------------------------------------------------------

  ALTER TABLE "HR"."COURIER" ADD CONSTRAINT "COURIER_OFFICE_FK" FOREIGN KEY ("OFFICE_ID_OFFICE")
	  REFERENCES "HR"."OFFICE" ("ID_OFFICE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PACKAGE
--------------------------------------------------------

  ALTER TABLE "HR"."PACKAGE" ADD CONSTRAINT "PACKAGE_INFO_PACKAGE_FK" FOREIGN KEY ("INFO_PACKAGE_ID")
	  REFERENCES "HR"."INFO_PACKAGE" ("ID_INFO_PAKAGE") ENABLE;
  ALTER TABLE "HR"."PACKAGE" ADD CONSTRAINT "PACKAGE_PACKAGE_SATUS_FK" FOREIGN KEY ("PACKAGE_SATUS_ID")
	  REFERENCES "HR"."PACKAGE_SATUS" ("ID_STATUS_PACKAGE") ENABLE;
  ALTER TABLE "HR"."PACKAGE" ADD CONSTRAINT "PACKAGE_REGISTRY_FK" FOREIGN KEY ("REGISTRY_ID_REGISTRY")
	  REFERENCES "HR"."REGISTRY" ("ID_REGISTRY") ENABLE;
  ALTER TABLE "HR"."PACKAGE" ADD CONSTRAINT "PACKAGE_TYPE_PACKAGE_FK" FOREIGN KEY ("TYPE_PACKAGE_ID")
	  REFERENCES "HR"."TYPE_PACKAGE" ("ID_TYPE_PACKAGE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTRY
--------------------------------------------------------

  ALTER TABLE "HR"."REGISTRY" ADD CONSTRAINT "REGISTRY_CLIENT_FK" FOREIGN KEY ("CLIENT_ID_CLIENT")
	  REFERENCES "HR"."CLIENT" ("ID_CLIENT") ENABLE;
  ALTER TABLE "HR"."REGISTRY" ADD CONSTRAINT "REGISTRY_COURIER_FK" FOREIGN KEY ("COURIER_ID_COURIER")
	  REFERENCES "HR"."COURIER" ("ID_COURIER") ENABLE;
  ALTER TABLE "HR"."REGISTRY" ADD CONSTRAINT "REGISTRY_TRANSPORT_PACKAGE_FK" FOREIGN KEY ("TRANSP_PACKAGE_ID")
	  REFERENCES "HR"."TRANSPORT_PACKAGE" ("ID_TRANSPORT_PACKAGE") ENABLE;
